# Generated by Django 4.2.5 on 2023-10-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="avatars/default.png", upload_to="avatars"),
        ),
    ]
