image: node

before_script: []
pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - mv frontend/* ./
    - npm install
    - npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
