# Generated by Django 4.2.5 on 2023-10-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0001_initial"),
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="folders.folder"
            ),
        ),
        migrations.DeleteModel(
            name="Folder",
        ),
    ]
