# Generated by Django 4.2.5 on 2023-10-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_alter_note_folder_delete_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
